import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

interface InvoicePdfData {
  invoiceId: string;
  workspaceName: string;
  currency: string;
  customerName: string;
  customerAddress?: string | null;
  agentName: string;
  createdAt: Date;
  paymentStatus: string;
  items: { productName: string; quantity: number; unitPrice: number }[];
  total: number;
}

/**
 * Renders a one-page invoice PDF into an in-memory buffer with pdfkit
 * (pure JS, no native/system dependency like wkhtmltopdf or a headless
 * browser — important for a low-resource deployment target).
 */
@Injectable()
export class InvoicePdfService {
  async render(data: InvoicePdfData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).fillColor('#0F7A5C').text(data.workspaceName, { continued: false });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#6B7772').text('INVOICE');
      doc.fontSize(9).fillColor('#6B7772').text(`#${data.invoiceId}`);
      doc.moveDown(1);

      // Meta
      doc.fontSize(10).fillColor('#1A1F1D');
      doc.text(`Date: ${data.createdAt.toLocaleDateString()}`);
      doc.text(`Billed to: ${data.customerName}`);
      if (data.customerAddress) doc.text(data.customerAddress);
      doc.text(`Delivered by: ${data.agentName}`);
      doc.text(`Payment status: ${data.paymentStatus}`);
      doc.moveDown(1);

      // Line items table (simple, no external table lib)
      const tableTop = doc.y;
      const col = { name: 50, qty: 320, price: 390, total: 470 };
      doc.fontSize(10).fillColor('#6B7772');
      doc.text('Item', col.name, tableTop);
      doc.text('Qty', col.qty, tableTop);
      doc.text('Unit', col.price, tableTop);
      doc.text('Total', col.total, tableTop);
      doc.moveTo(50, tableTop + 15).lineTo(545, tableTop + 15).strokeColor('#E1E7E4').stroke();

      let y = tableTop + 24;
      doc.fillColor('#1A1F1D');
      for (const item of data.items) {
        const lineTotal = item.quantity * item.unitPrice;
        doc.fontSize(10);
        doc.text(item.productName, col.name, y, { width: 260 });
        doc.text(String(item.quantity), col.qty, y);
        doc.text(money(item.unitPrice, data.currency), col.price, y);
        doc.text(money(lineTotal, data.currency), col.total, y);
        y += 20;
      }

      doc.moveTo(50, y + 4).lineTo(545, y + 4).strokeColor('#E1E7E4').stroke();
      doc.fontSize(12).fillColor('#1A1F1D').text('Total', col.price, y + 14);
      doc.fontSize(12).text(money(data.total, data.currency), col.total, y + 14);

      doc.fontSize(8).fillColor('#6B7772').text(
        'Generated by Simuni — simple connection between businesses, agents, customers, and deliveries.',
        50,
        760,
        { align: 'center', width: 495 },
      );

      doc.end();
    });
  }
}

function money(amount: number, currency: string): string {
  return `${currency} ${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}
