export interface AddisLocationPreset {
  id: string;
  name: string;
  amharicName?: string;
  subCity: string;
  sector: 'YEKA' | 'MERCATO' | 'BOLE' | 'CENTRAL' | 'KOLFE' | 'AKAKI' | 'ARADA' | 'LEBU';
  type: 'MALL' | 'HOTEL_RESTAURANT' | 'CAFE' | 'INSTITUTION' | 'WHOLESALE' | 'SUPERMARKET' | 'RETAILER';
  lat: number;
  lng: number;
  description: string;
  defaultCategory: 'Supermarket' | 'Hotel/Restaurant' | 'Wholesale' | 'Retailer' | 'Other';
}

export const ADDIS_ABABA_CENTRAL_LOCATION = {
  name: 'Addis Ababa Central Hub (Piazza / Churchill)',
  lat: 9.0227,
  lng: 38.7469,
  zoom: 12,
};

export const ADDIS_ABABA_TAGGED_LOCATIONS: AddisLocationPreset[] = [
  // =========================================================================
  // 1. SHOPPING MALLS & COMMERCIAL CENTERS
  // =========================================================================
  {
    id: 'mall-edna',
    name: 'Edna Mall & Multiplex',
    amharicName: 'ኤድና ሞል',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'MALL',
    lat: 8.9985,
    lng: 38.7865,
    description: 'Premier entertainment and retail shopping mall in Bole',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'mall-century',
    name: 'Century Mall (Gurd Shola)',
    amharicName: 'ሴንቸሪ ሞል',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'MALL',
    lat: 9.0182,
    lng: 38.8258,
    description: 'Major multi-story shopping mall and cinema at Gurd Shola / CMC axis',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'mall-diaspora',
    name: 'Diaspora Square Mall (Megenagna)',
    amharicName: 'ዳያስፖራ ሞል መገናኛ',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'MALL',
    lat: 9.0212,
    lng: 38.8021,
    description: 'High foot-traffic retail and electronics mall in Megenagna hub',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'mall-dembel',
    name: 'Dembel City Center (Olupe)',
    amharicName: 'ደምበል ሲቲ ሴንተር',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'MALL',
    lat: 9.0068,
    lng: 38.7675,
    description: 'Landmark shopping mall on Africa Avenue with banks, cafes & fashion',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'mall-getu',
    name: 'Getu Commercial Center',
    amharicName: 'ጌቱ ኮሜርሻል ሴንተር',
    subCity: 'Kirkos',
    sector: 'BOLE',
    type: 'MALL',
    lat: 9.0035,
    lng: 38.7735,
    description: 'Prominent commercial center with restaurants, retail outlets and offices',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'mall-morning-star',
    name: 'Morning Star Mall (Bole Medhanialem)',
    amharicName: 'ሞርኒንግ ስታር ሞል',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'MALL',
    lat: 8.9972,
    lng: 38.7885,
    description: 'Modern shopping complex with supermarkets and specialty boutiques',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'mall-zefmesh',
    name: 'Zefmesh Grand Mall (Megenagna)',
    amharicName: 'ዘፍመሽ ግራንድ ሞል',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'MALL',
    lat: 9.0225,
    lng: 38.8015,
    description: 'One of Addis Ababa’s largest multi-tenant shopping complexes',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'mall-berhane-adere',
    name: 'Berhane Adere Mall (Bole 22)',
    amharicName: 'ብርሃኔ አደሬ ሞል',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'MALL',
    lat: 9.0145,
    lng: 38.7840,
    description: 'Bole 22 Mazoriya shopping center with FMCG stores and dining',
    defaultCategory: 'Supermarket',
  },

  // =========================================================================
  // 2. RESTAURANTS & HOTELS (HORECA)
  // =========================================================================
  {
    id: 'hotel-skylight',
    name: 'Ethiopian Skylight Hotel',
    amharicName: 'ስካይላይት ሆቴል',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'HOTEL_RESTAURANT',
    lat: 8.9890,
    lng: 38.7895,
    description: 'Largest 5-star hotel in Africa, massive hospitality & banquet demand',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'hotel-sheraton',
    name: 'Sheraton Addis Luxury Collection',
    amharicName: 'ሸራተን አዲስ',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'HOTEL_RESTAURANT',
    lat: 9.0185,
    lng: 38.7595,
    description: 'Luxury hotel, fine dining, international diplomatic catering hub',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'hotel-hilton',
    name: 'Hilton Addis Ababa',
    amharicName: 'ሂልተን ሆቴል',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'HOTEL_RESTAURANT',
    lat: 9.0195,
    lng: 38.7640,
    description: 'Historic business hotel near ECA and Menelik II Avenue',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'hotel-hyatt-regency',
    name: 'Hyatt Regency (Meskel Square)',
    amharicName: 'ሀያት ሪጀንሲ',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'HOTEL_RESTAURANT',
    lat: 9.0110,
    lng: 38.7625,
    description: 'Luxury hotel overlooking Meskel Square with restaurants and bars',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'hotel-radisson-blu',
    name: 'Radisson Blu Hotel (Kazanchis)',
    amharicName: 'ራዲሰን ብሉ',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'HOTEL_RESTAURANT',
    lat: 9.0180,
    lng: 38.7725,
    description: 'Diplomatic hub hotel in Kazanchis UN-ECA quarter',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'hotel-marriott-exec',
    name: 'Marriott Executive Apartments',
    amharicName: 'ማሪዮት አፓርትመንትስ',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'HOTEL_RESTAURANT',
    lat: 9.0135,
    lng: 38.7635,
    description: 'Luxury extended stay hospitality property near Meskel Square',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'rest-yod-abyssinia',
    name: 'Yod Abyssinia Cultural Restaurant (Bole & CMC)',
    amharicName: 'ዮድ አቢሲኒያ የባህል ምግብ',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'HOTEL_RESTAURANT',
    lat: 8.9915,
    lng: 38.7830,
    description: 'High-volume traditional restaurant and tourist dining hub',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'rest-2000-habesha',
    name: '2000 Habesha Cultural Restaurant',
    amharicName: '2000 ሐበሻ የባህል ምግብ',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'HOTEL_RESTAURANT',
    lat: 8.9995,
    lng: 38.7845,
    description: 'Iconic traditional restaurant in the heart of Bole Atlas',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'rest-castellis',
    name: 'Ristorante Castelli (Piazza)',
    amharicName: 'ካስቴሊ ሬስቶራንት',
    subCity: 'Arada',
    sector: 'ARADA',
    type: 'HOTEL_RESTAURANT',
    lat: 9.0345,
    lng: 38.7525,
    description: 'Legendary Italian fine dining destination established in 1948',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'rest-kategna-bole',
    name: 'Kategna Restaurant (Bole Medhanialem)',
    amharicName: 'ቃተኛ ሬስቶራንት',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'HOTEL_RESTAURANT',
    lat: 8.9965,
    lng: 38.7880,
    description: 'Top-tier Ethiopian cuisine restaurant chain with high daily cover count',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'rest-bilen-kitfo',
    name: 'Bilen (ብሌን) ክትፎ (Yeka Abado)',
    amharicName: 'ብሌን ክትፎ አባዶ',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'HOTEL_RESTAURANT',
    lat: 9.0655,
    lng: 38.8632,
    description: 'Prominent restaurant and butcher eatery in Yeka Abado corridor',
    defaultCategory: 'Hotel/Restaurant',
  },

  // =========================================================================
  // 3. CAFES & ROASTERIES
  // =========================================================================
  {
    id: 'cafe-tomoca-piazza',
    name: 'Tomoca Coffee Heritage Roastery (Piazza)',
    amharicName: 'ቶሞካ ቡና ፒያሳ',
    subCity: 'Arada',
    sector: 'ARADA',
    type: 'CAFE',
    lat: 9.0358,
    lng: 38.7512,
    description: 'Ethiopia’s most famous historic coffee roastery (Wavel Street, Piazza)',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'cafe-tomoca-bole',
    name: 'Tomoca Coffee (Bole Atlas / Airport)',
    amharicName: 'ቶሞካ ቡና ቦሌ',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'CAFE',
    lat: 9.0045,
    lng: 38.7835,
    description: 'High-traffic specialty coffee cafe on Namibia Street',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'cafe-kaldis-megenagna',
    name: 'Kaldi’s Coffee Central (Megenagna)',
    amharicName: 'ካልዲስ ቡና መገናኛ',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'CAFE',
    lat: 9.0205,
    lng: 38.8030,
    description: 'Flagship branch of Ethiopia’s largest cafe chain',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'cafe-kaldis-bole',
    name: 'Kaldi’s Coffee (Bole Medhanialem)',
    amharicName: 'ካልዲስ ቡና ቦሌ መድኃኔዓለም',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'CAFE',
    lat: 8.9990,
    lng: 38.7875,
    description: 'Busy cafe and breakfast spot next to Medhanialem Cathedral',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'cafe-enrico-pastry',
    name: 'Enrico Pastry (Piazza Churchill)',
    amharicName: 'ኤንሪኮ ኬክ ቤት',
    subCity: 'Arada',
    sector: 'ARADA',
    type: 'CAFE',
    lat: 9.0335,
    lng: 38.7510,
    description: 'Historic pastry, mille-feuille and espresso house in Piazza',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'cafe-babi-bakery',
    name: 'Babi’s Bistro & Bakery (Bole Tele)',
    amharicName: 'ባቢስ ቤከሪ ቦሌ',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'CAFE',
    lat: 9.0010,
    lng: 38.7790,
    description: 'Artisan bakery, sandwich bistro, and specialty drinks',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'cafe-city-burgers-abado',
    name: 'City Burgers & Cafe (Yeka Abado)',
    amharicName: 'ሲቲ በርገር እና ካፌ አባዶ',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'CAFE',
    lat: 9.0657,
    lng: 38.8669,
    description: 'Popular fast-casual burger cafe in Yeka Abado condominium market',
    defaultCategory: 'Hotel/Restaurant',
  },

  // =========================================================================
  // 4. INSTITUTIONS (UNIVERSITIES, HOSPITALS, GOV & DIPLOMATIC)
  // =========================================================================
  {
    id: 'inst-au-hq',
    name: 'African Union Headquarters (AU HQ)',
    amharicName: 'የአፍሪካ ህብረት ዋና መሥሪያ ቤት',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'INSTITUTION',
    lat: 9.0018,
    lng: 38.7360,
    description: 'Pan-African continental headquarters and conference center',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-un-eca',
    name: 'UN-ECA Africa Hall Complex',
    amharicName: 'የተባበሩት መንግስታት የኢኮኖሚ ኮሚሽን (ኢሲኤ)',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'INSTITUTION',
    lat: 9.0175,
    lng: 38.7670,
    description: 'United Nations Economic Commission for Africa headquarters',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-aau-6kilo',
    name: 'Addis Ababa University (6 Kilo Main Campus)',
    amharicName: 'አዲስ አበባ ዩኒቨርሲቲ (6 ኪሎ)',
    subCity: 'Arada',
    sector: 'ARADA',
    type: 'INSTITUTION',
    lat: 9.0475,
    lng: 38.7595,
    description: 'Main university campus, massive student and faculty dining market',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-aau-4kilo',
    name: 'AAU College of Natural Sciences (4 Kilo)',
    amharicName: 'አዲስ አበባ ዩኒቨርሲቲ (4 ኪሎ)',
    subCity: 'Arada',
    sector: 'ARADA',
    type: 'INSTITUTION',
    lat: 9.0340,
    lng: 38.7610,
    description: 'Science campus near King George VI street and parliament',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-black-lion',
    name: 'Tikur Anbessa (Black Lion) Specialized Hospital',
    amharicName: 'ጥቁር አንበሳ ስፔሻላይዝድ ሆስፒታል',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'INSTITUTION',
    lat: 9.0170,
    lng: 38.7490,
    description: 'Ethiopia’s largest tertiary referral hospital and medical school',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-st-paul',
    name: 'St. Paul’s Hospital Millennium Medical College',
    amharicName: 'ቅዱስ ጳውሎስ ሆስፒታል',
    subCity: 'Gullele',
    sector: 'MERCATO',
    type: 'INSTITUTION',
    lat: 9.0520,
    lng: 38.7290,
    description: 'Major specialized hospital and public health medical college',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-ethio-telecom-hq',
    name: 'Ethio Telecom Head Office (Churchill Ave)',
    amharicName: 'ኢትዮ ቴሌኮም ዋና መ/ቤት',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'INSTITUTION',
    lat: 9.0175,
    lng: 38.7515,
    description: 'National telecom operator headquarters, key partner operations site',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-cbe-hq',
    name: 'Commercial Bank of Ethiopia (CBE) Tower',
    amharicName: 'የኢትዮጵያ ንግድ ባንክ ዋና ህንፃ',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'INSTITUTION',
    lat: 9.0205,
    lng: 38.7525,
    description: 'Tallest skyscraper in East Africa (Ras Desta Damtew St)',
    defaultCategory: 'Other',
  },
  {
    id: 'inst-rufael-school',
    name: 'Rufael School & Compound (Yeka Abado)',
    amharicName: 'ሩፋኤል ትምህርት ቤት አባዶ',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'INSTITUTION',
    lat: 9.0636,
    lng: 38.8619,
    description: 'Educational institution with daily canteen and student grocery demand',
    defaultCategory: 'Other',
  },

  // =========================================================================
  // 5. SUPERMARKETS & GROCERIES
  // =========================================================================
  {
    id: 'super-safeway-bole',
    name: 'Safeway Supermarket (Gerji)',
    amharicName: 'ሴፍዌይ ሱፐርማርኬት ገርጂ',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'SUPERMARKET',
    lat: 9.0035,
    lng: 38.8080,
    description: 'High-volume packaged grocery and bottled beverage retailer',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'super-fantu-bole',
    name: 'Fantu Supermarket (Bole Medhanialem)',
    amharicName: 'ፋንቱ ሱፐርማርኬት',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'SUPERMARKET',
    lat: 8.9975,
    lng: 38.7890,
    description: 'Pioneer premium grocery supermarket with high bottled water turnaround',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'super-fresh-corner-atlas',
    name: 'Fresh Corner Supermarket (Atlas)',
    amharicName: 'ፍሬሽ ኮርነር አትላስ',
    subCity: 'Bole',
    sector: 'BOLE',
    type: 'SUPERMARKET',
    lat: 9.0062,
    lng: 38.7845,
    description: 'Premium grocery chain catering to HoReCa and neighborhood households',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'super-all-mart-cmc',
    name: 'All-Mart Supermarket (CMC Michael)',
    amharicName: 'ኦል ማርት ሱፐርማርኬት ሲኤምሲ',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'SUPERMARKET',
    lat: 9.0215,
    lng: 38.8425,
    description: 'Large neighborhood supermarket serving CMC & Ayat residential estates',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'super-queen-supermarket',
    name: 'Queens Supermarket (Kazanchis / ECA)',
    amharicName: 'ኩዊንስ ሱፐርማርኬት',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    type: 'SUPERMARKET',
    lat: 9.0190,
    lng: 38.7690,
    description: 'Government/MIDROC retail supermarket chain branch',
    defaultCategory: 'Supermarket',
  },

  // =========================================================================
  // 6. WHOLESALE & RESIDENTIAL HUBS (FMCG BEVERAGE DEMAND)
  // =========================================================================
  {
    id: 'yeka-abado',
    name: 'Yeka Abado Condominium & Market Hub',
    amharicName: 'የካ አባዶ ኮንዶሚኒየም',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'RETAILER',
    lat: 9.0665,
    lng: 38.8720,
    description: 'Major residential & retail hub in eastern Addis Ababa',
    defaultCategory: 'Retailer',
  },
  {
    id: 'yeka-ayat',
    name: 'Ayat Zone 2 / 3 Commercial Center',
    amharicName: 'አያት የንግድ ማዕከል',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'SUPERMARKET',
    lat: 9.0195,
    lng: 38.8520,
    description: 'Ayat light-rail terminus, high-density residential shops',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'yeka-kotebe',
    name: 'Kotebe / 02 Meta Brewery Corridor',
    amharicName: 'ኮተቤ / 02',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'WHOLESALE',
    lat: 9.0345,
    lng: 38.8350,
    description: 'Beverage retail and wholesale cluster along Kotebe road',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'mercato-autobis-tera',
    name: 'Mercato Autobis Tera Wholesale',
    amharicName: 'መርካቶ አውቶቢስ ተራ',
    subCity: 'Addis Ketema',
    sector: 'MERCATO',
    type: 'WHOLESALE',
    lat: 9.0325,
    lng: 38.7345,
    description: 'Ethiopia’s premier FMCG wholesale and truck offloading sector',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'mercato-bomb-tera',
    name: 'Mercato Bomb Tera Household & Provisions',
    amharicName: 'መርካቶ ቦምብ ተራ',
    subCity: 'Addis Ketema',
    sector: 'MERCATO',
    type: 'WHOLESALE',
    lat: 9.0305,
    lng: 38.7360,
    description: 'Key depot for packaged beverages and groceries',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'kolfe-anfo',
    name: 'Kolfe Anfo / 18 Area Marts',
    amharicName: 'ቆልፌ አንፎ',
    subCity: 'Kolfe Keranio',
    sector: 'KOLFE',
    type: 'RETAILER',
    lat: 9.0229,
    lng: 38.6721,
    description: 'Western suburban retail shops and kiosk clusters',
    defaultCategory: 'Retailer',
  },
  {
    id: 'lebu-musika-bet',
    name: 'Lebu Musika Bet & Jemo Roundabout',
    amharicName: 'ሌቡ ሙዚቃ ቤት / ጀምሮ',
    subCity: 'Nefas Silk / Lebu',
    sector: 'LEBU',
    type: 'SUPERMARKET',
    lat: 8.9720,
    lng: 38.7180,
    description: 'Dense residential retail and wholesale distributors',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'jemo-1-condo',
    name: 'Jemo 1 / 2 Commercial Village',
    amharicName: 'ጀሞ 1 / 2 ኮንዶሚኒየም',
    subCity: 'Nefas Silk',
    sector: 'LEBU',
    type: 'RETAILER',
    lat: 8.9610,
    lng: 38.7050,
    description: 'High-population residential market and mini-marts',
    defaultCategory: 'Retailer',
  },
  {
    id: 'kaliti-customs',
    name: 'Akaki Kaliti Heavy Freight & Customs Terminal',
    amharicName: 'ቃሊቲ ጉምሩክ እና ጭነት',
    subCity: 'Akaki Kaliti',
    sector: 'AKAKI',
    type: 'WHOLESALE',
    lat: 8.8950,
    lng: 38.7620,
    description: 'Industrial zone, logistics warehouse, and bulk buyers',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'abado-meskelenya',
    name: 'አባዶ መስቀለኛ (Yeka Abado Junction)',
    amharicName: 'አባዶ መስቀለኛ',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'RETAILER',
    lat: 9.0641,
    lng: 38.8735,
    description: 'Crucial transport junction and local retail shopping strip',
    defaultCategory: 'Retailer',
  },
  {
    id: 'abado-g7-square',
    name: 'አባዶ አደባባይ G7 (Yeka Abado G-7 Square)',
    amharicName: 'አባዶ አደባባይ ጂ 7',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'RETAILER',
    lat: 9.0675,
    lng: 38.8728,
    description: 'Central transport and commerce hub in Yeka Abado condominium',
    defaultCategory: 'Retailer',
  },
  {
    id: 'abado-site-1-blocks',
    name: 'አባዶ ሳይት 1 ኮንዶሚኒየም (Yeka Abado Site 1)',
    amharicName: 'አባዶ ሳይት 1',
    subCity: 'Yeka',
    sector: 'YEKA',
    type: 'RETAILER',
    lat: 9.0665,
    lng: 38.8655,
    description: 'Dense residential condominium blocks and ground floor markets',
    defaultCategory: 'Retailer',
  },
];
