export interface AddisLocationPreset {
  id: string;
  name: string;
  amharicName?: string;
  subCity: string;
  sector: 'YEKA' | 'MERCATO' | 'BOLE' | 'CENTRAL' | 'KOLFE' | 'AKAKI' | 'ARADA' | 'LEBU';
  lat: number;
  lng: number;
  description: string;
  defaultCategory?: string;
}

export const ADDIS_ABABA_CENTRAL_LOCATION = {
  name: 'Addis Ababa Central Hub (Piazza / Churchill)',
  lat: 9.0227,
  lng: 38.7469,
  zoom: 12,
};

export const ADDIS_ABABA_TAGGED_LOCATIONS: AddisLocationPreset[] = [
  // 1. Yeka / East Corridor (Water Bottling & Abado hubs)
  {
    id: 'yeka-abado',
    name: 'Yeka Abado Condominium & Market',
    amharicName: 'የካ አባዶ ኮንዶሚኒየም',
    subCity: 'Yeka',
    sector: 'YEKA',
    lat: 9.0255,
    lng: 38.8150,
    description: 'Major residential & retail hub in eastern Addis Ababa',
    defaultCategory: 'Retailer',
  },
  {
    id: 'yeka-ayat',
    name: 'Ayat Zone 2 / 3 Commercial Center',
    amharicName: 'አያት የንግድ ማዕከል',
    subCity: 'Yeka',
    sector: 'YEKA',
    lat: 9.0195,
    lng: 38.8520,
    description: 'Ayat light-rail terminus, high-density residential shops',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'yeka-kotebe',
    name: 'Kotebe / 02 Meta Brewery Corridor',
    amharicName: 'ኮተቤ / 02',
    subCity: 'Yeka',
    sector: 'YEKA',
    lat: 9.0345,
    lng: 38.8350,
    description: 'Beverage retail and wholesale cluster along Kotebe road',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'yeka-gurd-shola',
    name: 'Gurd Shola Athletics & Wholesale',
    amharicName: 'ጉርድ ሾላ',
    subCity: 'Yeka',
    sector: 'YEKA',
    lat: 9.0174,
    lng: 38.8249,
    description: 'High-traffic commercial distribution axis near CMC',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'yeka-cmc',
    name: 'CMC Michael Commercial Strip',
    amharicName: 'ሲኤምሲ ሚካኤል',
    subCity: 'Yeka',
    sector: 'YEKA',
    lat: 9.0210,
    lng: 38.8410,
    description: 'Supermarkets, restaurants, and residential retail',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'yeka-megenagna',
    name: 'Megenagna Transit Square & Diaspora Mall',
    amharicName: 'መገናኛ አደባባይ',
    subCity: 'Yeka',
    sector: 'YEKA',
    lat: 9.0212,
    lng: 38.8021,
    description: 'Sub-city main transport terminal and commercial malls',
    defaultCategory: 'Supermarket',
  },

  // 2. Mercato / Addis Ketema (Wholesale & FMCG Capital)
  {
    id: 'mercato-autobis-tera',
    name: 'Mercato Autobis Tera Wholesale',
    amharicName: 'መርካቶ አውቶቢስ ተራ',
    subCity: 'Addis Ketema',
    sector: 'MERCATO',
    lat: 9.0325,
    lng: 38.7345,
    description: 'Ethiopia’s premier FMCG wholesale and truck offloading sector',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'mercato-shema-tera',
    name: 'Mercato Shema Tera & Berbere Tera',
    amharicName: 'መርካቶ ሸማ ተራ',
    subCity: 'Addis Ketema',
    sector: 'MERCATO',
    lat: 9.0350,
    lng: 38.7390,
    description: 'Dense daily foot-traffic commodity markets',
    defaultCategory: 'Retailer',
  },
  {
    id: 'mercato-bomb-tera',
    name: 'Mercato Bomb Tera Household & Provisions',
    amharicName: 'መርካቶ ቦምብ ተራ',
    subCity: 'Addis Ketema',
    sector: 'MERCATO',
    lat: 9.0305,
    lng: 38.7360,
    description: 'Key depot for packaged beverages and groceries',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'kolfe-anfo',
    name: 'Kolfe Anfo / 18 Area Marts',
    amharicName: 'ቆልፌ አንፎ',
    subCity: 'Kolfe Keranio',
    sector: 'KOLFE',
    lat: 9.0229,
    lng: 38.6721,
    description: 'Western suburban retail shops and kiosk clusters',
    defaultCategory: 'Retailer',
  },
  {
    id: 'burayu-checkpoint',
    name: 'Burayu Gate / Gefersa Corridor',
    amharicName: 'ቡራዩ ኬላ / ገፈርሳ',
    subCity: 'Kolfe / Burayu',
    sector: 'MERCATO',
    lat: 9.0430,
    lng: 38.6510,
    description: 'Western industrial & fast-moving goods gateway',
    defaultCategory: 'Wholesale',
  },

  // 3. Bole / South-East Corridor (HoReCa & Premium Supermarkets)
  {
    id: 'bole-medhanialem',
    name: 'Bole Medhanialem & Edna Mall Hub',
    amharicName: 'ቦሌ መድኃኔዓለም',
    subCity: 'Bole',
    sector: 'BOLE',
    lat: 8.9985,
    lng: 38.7865,
    description: 'Major HoReCa, luxury supermarkets, and cafe strip',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'bole-atlas',
    name: 'Bole Atlas / Shala Park Corridor',
    amharicName: 'ቦሌ አትላስ',
    subCity: 'Bole',
    sector: 'BOLE',
    lat: 9.0062,
    lng: 38.7845,
    description: 'Hotels, nightlife, eateries, and beverage retail',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'bole-airport-cargo',
    name: 'Bole International Cargo & Airport Strip',
    amharicName: 'ቦሌ አውሮፕላን ማረፊያ',
    subCity: 'Bole',
    sector: 'BOLE',
    lat: 8.9806,
    lng: 38.7997,
    description: 'Institutional catering and logistics depots',
    defaultCategory: 'Other',
  },
  {
    id: 'bole-gerji',
    name: 'Gerji Imperial / Unity Park Zone',
    amharicName: 'ገርጂ ኢምፔሪያል',
    subCity: 'Bole',
    sector: 'BOLE',
    lat: 9.0020,
    lng: 38.8050,
    description: 'Dense residential neighborhood groceries and kiosks',
    defaultCategory: 'Retailer',
  },
  {
    id: 'bole-bulbula',
    name: 'Bole Bulbula 93 Mazoriya',
    amharicName: 'ቦሌ ቡልቡላ 93 ማዞሪያ',
    subCity: 'Bole',
    sector: 'BOLE',
    lat: 8.9650,
    lng: 38.7810,
    description: 'Growing residential condominiums and supermarkets',
    defaultCategory: 'Supermarket',
  },

  // 4. Central / Arada / Kirkos (City Center & Government / Commercial Hubs)
  {
    id: 'piazza-de-gaulle',
    name: 'Piazza / De Gaulle Commercial Square',
    amharicName: 'ፒያሳ ደጎል አደባባይ',
    subCity: 'Arada',
    sector: 'ARADA',
    lat: 9.0352,
    lng: 38.7518,
    description: 'Historic trade center, retail boutiques, and cafes',
    defaultCategory: 'Retailer',
  },
  {
    id: 'churchill-avenue',
    name: 'Churchill Avenue & Cinema Ras Corridor',
    amharicName: 'ቸርችል ጎዳና / ሲኒማ ራስ',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    lat: 9.0227,
    lng: 38.7510,
    description: 'Central business district with commercial towers and eateries',
    defaultCategory: 'Retailer',
  },
  {
    id: 'mexico-square',
    name: 'Mexico Square Commercial Center',
    amharicName: 'ሜክሲኮ አደባባይ',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    lat: 9.0105,
    lng: 38.7450,
    description: 'Heavy commuter crossroads, wholesale agencies and kiosks',
    defaultCategory: 'Wholesale',
  },
  {
    id: 'sarbet-au',
    name: 'Sarbet / African Union Headquarter Strip',
    amharicName: 'ሳርቤት / አፍሪካ ህብረት',
    subCity: 'Kirkos',
    sector: 'CENTRAL',
    lat: 9.0015,
    lng: 38.7360,
    description: 'International diplomatic zone and high-end restaurants',
    defaultCategory: 'Hotel/Restaurant',
  },
  {
    id: 'gotera-interchange',
    name: 'Gotera Interchange & Pepsi Factory Corridor',
    amharicName: 'ጎተራ ማሳለጫ',
    subCity: 'Kirkos / Nefas Silk',
    sector: 'CENTRAL',
    lat: 8.9890,
    lng: 38.7550,
    description: 'Industrial warehousing and soft-drink distribution route',
    defaultCategory: 'Wholesale',
  },

  // 5. Southern / Nefas Silk / Lebu Corridor
  {
    id: 'lebu-musika-bet',
    name: 'Lebu Musika Bet & Jemo Roundabout',
    amharicName: 'ሌቡ ሙዚቃ ቤት / ጀምሮ',
    subCity: 'Nefas Silk / Lebu',
    sector: 'LEBU',
    lat: 8.9720,
    lng: 38.7180,
    description: 'Dense residential retail and wholesale distributors',
    defaultCategory: 'Supermarket',
  },
  {
    id: 'jemo-1-condo',
    name: 'Jemo 1 / 2 Commercial Village',
    amharicName: 'ጀሞ 1 / 2 ኮንዶሚኒየም',
    subCity: 'Nefas Silk',
    sector: 'LEBU',
    lat: 8.9610,
    lng: 38.7050,
    description: 'High-population residential market and mini-marts',
    defaultCategory: 'Retailer',
  },
  {
    id: 'kaliti-customs',
    name: 'Akaki Kaliti Heavy Freight & Customs Terminal',
    amharicName: 'ቃሊቲ ጉምሩክ እና ጭነት',
    subCity: 'Akaki Kaliti',
    sector: 'AKAKI',
    lat: 8.8950,
    lng: 38.7620,
    description: 'Industrial zone, logistics warehouse, and bulk buyers',
    defaultCategory: 'Wholesale',
  },
];
